# metrics-server-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-server-certs
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
