# metrics-server-fixed.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      labels:
        k8s-app: metrics-server
    spec:
      containers:
        - args:
            - --cert-dir=/tmp
            - --kubelet-insecure-tls
            - --kubelet-preferred-address-types=InternalIP
          image: k8s.gcr.io/metrics-server/metrics-server:v0.6.1
          name: metrics-server
          volumeMounts:
            - mountPath: /tmp
              name: tmp-dir
      volumes:
        - emptyDir: {}
          name: tmp-dir
